export const LIST_ALL = 'LIST_ALL';
export const SEARCH_PAGE = 'SEARCH_PAGE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_PRODUCT_IN_CART = 'DELETE_PRODUCT_IN_CART';
export const UPDATE_PRODUCT_IN_CART = 'UPDATE_PRODUCT_IN_CART';